# load packages
library(modelr)
library(dplyr)
library(purrr)
library(tidyr)
library(ggplot2)
library(qgraph)
#library(psychonetrics)
# library(bootnet)
library(rootSolve)
library(deSolve)
library(ggpubr)
library(magrittr)
library(stringr)