name: CI Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Replace with your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Install pytest or any other dependencies you need
          # Add any additional dependencies below if needed
          # pip install <other-package-name>

      - name: Run Tests
        run: |
          # Run your tests here, for example:
          pytest  # Replace with your actual test command

